[package]
name = "tavo-ai"
version = "0.4.0"
edition = "2021"
description = "Tavo AI SDK for Rust"
license = "Apache-2.0"
repository = "https://github.com/TavoAI/tavo-sdk"
homepage = "https://tavoai.github.io/tavo-sdk/"
documentation = "https://docs.rs/tavo-ai"
readme = "README.md"
keywords = ["tavo", "ai", "security", "scanning", "analysis"]
categories = ["api-bindings", "development-tools"]

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
url = "2.5"

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "basic_scan"
path = "examples/basic_scan.rs"