name: Publish Python SDK

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Update version
        run: |
          cd packages/python
          # Strip 'v' prefix if present and update version in pyproject.toml
          VERSION="${{ inputs.version }}"
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml

      - name: Build package
        run: |
          cd packages/python
          python -m build

      - name: Publish to TestPyPI
        if: contains(inputs.version, 'alpha') || contains(inputs.version, 'beta')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ !contains(inputs.version, 'alpha') && !contains(inputs.version, 'beta') }}
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag python-v${{ inputs.version }}
          git push origin python-v${{ inputs.version }}

      - name: Notify success
        run: |
          echo "✅ Python SDK v${{ inputs.version }} published successfully!"
          echo "📦 Available on PyPI: https://pypi.org/project/tavo-sdk/${{ inputs.version }}/"
