name: Publish JavaScript SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        type: string

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd packages/javascript
          yarn install --frozen-lockfile

      - name: Update version
        run: |
          cd packages/javascript
          # Strip 'v' prefix if present and update version in package.json
          VERSION="${{ inputs.version }}"
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

      - name: Build package
        run: |
          cd packages/javascript
          yarn build

      - name: Run tests
        run: |
          cd packages/javascript
          yarn test

      - name: Create ID Token
        uses: actions/create-id-token@v1
        with:
          audience: npm:registry.npmjs.org

      - name: Publish to npm
        run: |
          cd packages/javascript
          npm publish --access public --provenance

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag js-v${{ inputs.version }}
          git push origin js-v${{ inputs.version }}

      - name: Notify success
        run: |
          echo "✅ JavaScript SDK v${{ inputs.version }} published successfully!"
          echo "📦 Available on npm: https://www.npmjs.com/package/@tavoai/sdk/v/${{ inputs.version }}"
