name: Publish Go SDK

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string

jobs:
    publish:
        name: Publish to Go Module Registry
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Initialize submodules
              run: git submodule update --init --recursive

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21"

            - name: Update version
              run: |
                  cd packages/go
                  # Strip 'v' prefix if present and update version in go.mod
                  VERSION="${{ inputs.version }}"
                  VERSION=${VERSION#v}  # Remove 'v' prefix if present
                  # Go modules use semantic versioning, so we need to ensure the version is valid
                  # The version should already be in the correct format from the release workflow

            - name: Tidy dependencies
              run: |
                  cd packages/go
                  go mod tidy

            - name: Run tests
              run: |
                  cd packages/go
                  go test ./...

            - name: Build package
              run: |
                  cd packages/go
                  go build ./...

            - name: Create Git tag for Go module
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  # For Go modules, we create a tag with the module path + version
                  # The Go module in packages/go should have a module path like github.com/TavoAI/tavo-go-sdk
                  cd packages/go
                  MODULE_PATH=$(go list -m)
                  TAG_NAME="v${{ inputs.version }}"
                  git tag "$TAG_NAME"
                  git push origin "$TAG_NAME"

            - name: Notify success
              run: |
                  echo "✅ Go SDK v${{ inputs.version }} published successfully!"
                  echo "📦 Go module available at: https://pkg.go.dev/github.com/TavoAI/tavo-go-sdk@v${{ inputs.version }}"
