name: Publish .NET SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        type: string

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Update version
        run: |
          cd packages/dotnet
          # Update version in .csproj file
          sed -i "s/<Version>.*<\/Version>/<Version>${{ inputs.version }}<\/Version>/" TavoAI.csproj

      - name: Restore dependencies
        run: |
          cd packages/dotnet
          dotnet restore

      - name: Build package
        run: |
          cd packages/dotnet
          dotnet build --configuration Release

      - name: Run tests
        run: |
          cd packages/dotnet
          dotnet test --configuration Release

      - name: Pack NuGet package
        run: |
          cd packages/dotnet
          dotnet pack --configuration Release --output nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          cd packages/dotnet
          if [ -n "$NUGET_API_KEY" ]; then
            dotnet nuget push "nupkg/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
          else
            echo "NUGET_API_KEY secret not set, skipping NuGet publish"
          fi

      - name: Create source archive
        run: |
          cd packages/dotnet
          # Create source code archive
          tar -czf ../../tavo-dotnet-sdk-v${{ inputs.version }}-source.tar.gz .

      - name: Upload source archive to release
        run: |
          # Upload the source archive to the GitHub release
          gh release upload v${{ inputs.version }} ../tavo-dotnet-sdk-v${{ inputs.version }}-source.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify success
        run: |
          echo "✅ .NET SDK v${{ inputs.version }} published successfully!"
          echo "📦 Available on NuGet: https://www.nuget.org/packages/TavoAI.SDK/${{ inputs.version }}"
